import { QuickPickItem } from "vscode";

export class LanguageHelper {
    private static RFC4646LanguageTagList: QuickPickItem[] = [
        { label: 'en-US', description: 'English (United States)'},
        { label: 'fr-FR', description: 'French (France)'},
        { label: 'es-ES', description: 'Spanish (Spain)'},
        { label: 'de-DE', description: 'German (Germany)'},
        { label: 'ru-RU', description: 'Russian (Russia)'},
        { label: 'zh-chs', description: 'Chinese (Simplified)'},
        { label: 'zh-cht', description: 'Chinese (Traditional)'},
        { label: 'ko-KR', description: 'Korean (Korea)'},
        { label: 'ja-JP', description: 'Japanase (Japan)'},
        { label: 'it-IT', description: 'Italian (Italia)'},
        { label: 'da-DK', description: 'Danish (Denmark)'},
        { label: 'fi-FI', description: 'Finnish (Finland)'},
        { label: 'nl-NL', description: 'Dutch (Netherlands)'},
        { label: 'nb-NO', description: 'Norwegian Bokmål (Norway)'},
        { label: 'af-ZA', description: 'Afrikaans (South Africa)'},
        { label: 'sq-AL', description: 'Albanian (Albania)'},
        { label: 'gsw-FR', description: 'Alsatian (France)'},
        { label: 'am-ET', description: 'Amharic (Ethiopia)'},
        { label: 'ar-DZ', description: 'Arabic (Algeria)'},
        { label: 'ar-BH', description: 'Arabic (Bahrain)'},
        { label: 'ar-EG', description: 'Arabic (Egypt)'},
        { label: 'ar-IQ', description: 'Arabic (Iraq)'},
        { label: 'ar-JO', description: 'Arabic (Jordan)'},
        { label: 'ar-KW', description: 'Arabic (Kuwait)'},
        { label: 'ar-LB', description: 'Arabic (Lebanon)'},
        { label: 'ar-LY', description: 'Arabic (Libya)'},
        { label: 'ar-MA', description: 'Arabic (Morocco)'},
        { label: 'ar-OM', description: 'Arabic (Oman)'},
        { label: 'ar-QA', description: 'Arabic (Qatar)'},
        { label: 'ar-SA', description: 'Arabic (Saudi Arabia)'},
        { label: 'ar-SY', description: 'Arabic (Syria)'},
        { label: 'ar-TN', description: 'Arabic (Tunisia)'},
        { label: 'ar-AE', description: 'Arabic (U.A.E.)'},
        { label: 'ar-YE', description: 'Arabic (Yemen)'},
        { label: 'hy-AM', description: 'Armenian (Armenia)'},
        { label: 'as-IN', description: 'Assamese (India)'},
        { label: 'az-AZ', description: 'Azeri (Azerbaijan)'},
        { label: 'ba-RU', description: 'Bashkir (Russia)'},
        { label: 'eu-ES', description: 'Basque (Basque)'},
        { label: 'be-BY', description: 'Belarusian (Belarus)'},
        { label: 'bn-BD', description: 'Bengali (Bangladesh)'},
        { label: 'bs-Cyrl-BA', description: 'Bosnian (Cyrillic, Bosnia and Herzegovina)'},
        { label: 'bs-Latn-BA', description: 'Bosnian (Latin, Bosnia and Herzegovina)'},
        { label: 'br-FR', description: 'Breton (France)'},
        { label: 'bg-BG', description: 'Bulgarian (Bulgaria)'},
        { label: 'ca-ES', description: 'Catalan (Catalan)'},
        { label: 'zh-HK', description: 'Chinese (Hong Kong S.A.R.)'},
        { label: 'zh-MO', description: 'Chinese (Macao S.A.R.)'},
        { label: 'zh-CN', description: 'Chinese (People\'s Republic of China)'},
        { label: 'zh-SG', description: 'Chinese (Singapore)'},
        { label: 'zh-TW', description: 'Chinese (Taiwan)'},
        { label: 'co-FR', description: 'Corsican (France)'},
        { label: 'hr-HR', description: 'Croatian (Croatia)'},
        { label: 'hr-BA', description: 'Croatian (Latin, Bosnia and Herzegovina)'},
        { label: 'cs-CZ', description: 'Czech (Czech Republic)'},
        // { label: 'da-DK', description: 'Danish (Denmark)'},
        { label: 'prs-AF', description: 'Dari (Afghanistan)'},
        { label: 'div-MV', description: 'Divehi (Maldives)'},
        { label: 'nl-BE', description: 'Dutch (Belgium)'},
        // { label: 'nl-NL', description: 'Dutch (Netherlands)'},
        { label: 'en-AU', description: 'English (Australia)'},
        { label: 'en-BZ', description: 'English (Belize)'},
        { label: 'en-CA', description: 'English (Canada)'},
        { label: 'en-029', description: 'English (Caribbean)'},
        { label: 'en-IN', description: 'English (India)'},
        { label: 'en-IE', description: 'English (Ireland)'},
        { label: 'en-JM', description: 'English (Jamaica)'},
        { label: 'en-MY', description: 'English (Malaysia)'},
        { label: 'en-NZ', description: 'English (New Zealand)'},
        { label: 'en-PH', description: 'English (Republic of the Philippines)'},
        { label: 'en-SG', description: 'English (Singapore)'},
        { label: 'en-ZA', description: 'English (South Africa)'},
        { label: 'en-TT', description: 'English (Trinidad and Tobago)'},
        { label: 'en-GB', description: 'English (United Kingdom)'},
        // { label: 'en-US', description: 'English (United States)'},
        { label: 'en-ZW', description: 'English (Zimbabwe)'},
        { label: 'et-EE', description: 'Estonian (Estonia)'},
        { label: 'fo-FO', description: 'Faroese (Faroe Islands)'},
        { label: 'fil-PH', description: 'Filipino (Philippines)'},
        // { label: 'fi-FI', description: 'Finnish (Finland)'},
        { label: 'fr-BE', description: 'French (Belgium)'},
        { label: 'fr-CA', description: 'French (Canada)'},
        // { label: 'fr-FR', description: 'French (France)'},
        { label: 'fr-LU', description: 'French (Luxembourg)'},
        { label: 'fr-MC', description: 'French (Principality of Monaco)'},
        { label: 'fr-CH', description: 'French (Switzerland)'},
        { label: 'fy-NL', description: 'Frisian (Netherlands)'},
        { label: 'gl-ES', description: 'Galician (Galician)'},
        { label: 'ka-GE', description: 'Georgian (Georgia)'},
        { label: 'de-AT', description: 'German (Austria)'},
        // { label: 'de-DE', description: 'German (Germany)'},
        { label: 'de-LI', description: 'German (Liechtenstein)'},
        { label: 'de-LU', description: 'German (Luxembourg)'},
        { label: 'de-CH', description: 'German (Switzerland)'},
        { label: 'el-GR', description: 'Greek (Greece)'},
        { label: 'kl-GL', description: 'Greenlandic (Greenland)'},
        { label: 'gu-IN', description: 'Gujarati (India)'},
        { label: 'ha-NG', description: 'Hausa (Nigeria)'},
        { label: 'he-IL', description: 'Hebrew (Israel)'},
        { label: 'hi-IN', description: 'Hindi (India)'},
        { label: 'hu-HU', description: 'Hungarian (Hungary)'},
        { label: 'is-IS', description: 'Icelandic (Iceland)'},
        { label: 'ig-NG', description: 'Igbo (Nigeria)'},
        { label: 'id-ID', description: 'Indonesian (Indonesia)'},
        { label: 'iu-Latn-CA', description: 'Inuktitut (Latin, Canada)'},
        { label: 'iu-Cans-CA', description: 'Inuktitut (Syllabics, Canada)'},
        { label: 'ga-IE', description: 'Irish (Ireland)'},
        { label: 'xh-ZA', description: 'Xhosa (South Africa)'},
        { label: 'zu-ZA', description: 'Zulu (South Africa)'},
        { label: 'it-IT', description: 'Italian (Italy)'},
        { label: 'it-CH', description: 'Italian (Switzerland)'},
        { label: 'ja-JP', description: 'Japanese (Japan)'},
        { label: 'kn-IN', description: 'Kannada (India)'},
        { label: 'kk-KZ', description: 'Kazakh (Kazakhstan)'},
        { label: 'km-KH', description: 'Khmer (Cambodia)'},
        { label: 'qut-GT', description: 'K\'iche (Guatemala)'},
        { label: 'rw-RW', description: 'Kinyarwanda (Rwanda)'},
        { label: 'sw-KE', description: 'Kiswahili (Kenya)'},
        { label: 'kok-IN', description: 'Konkani (India)'},
        // { label: 'ko-KR', description: 'Korean (Korea)'},
        { label: 'ky-KG', description: 'Kyrgyz (Kyrgyzstan)'},
        { label: 'lo-LA', description: 'Lao (Lao P.D.R.)'},
        { label: 'lv-LV', description: 'Latvian (Latvia)'},
        { label: 'lt-LT', description: 'Lithuanian (Lithuania)'},
        { label: 'wee-DE', description: 'Lower Sorbian (Germany)'},
        { label: 'lb-LU', description: 'Luxembourgish (Luxembourg)'},
        { label: 'mk-MK', description: 'Macedonian (Former Yugoslav Republic of Macedonia)'},
        { label: 'ms-BN', description: 'Malay (Brunei Darussalam)'},
        { label: 'ms-MY', description: 'Malay (Malaysia)'},
        { label: 'ml-IN', description: 'Malayalam (India)'},
        { label: 'mt-MT', description: 'Maltese (Malta)'},
        { label: 'mi-NZ', description: 'Maori (New Zealand)'},
        { label: 'arn-CL', description: 'Mapudungun (Chile)'},
        { label: 'mr-IN', description: 'Marathi (India)'},
        { label: 'moh-CA', description: 'Mohawk (Mohawk)'},
        { label: 'mn-MN', description: 'Mongolian (Cyrillic, Mongolia)'},
        { label: 'mn-Mong-CN', description: 'Mongolian (Traditional Mongolian, PRC)'},
        { label: 'ne-NP', description: 'Nepali (Nepal)'},
        { label: 'nb-NO', description: 'Norwegian, Bokml (Norway)'},
        { label: 'nn-NO', description: 'Norwegian, Nynorsk (Norway)'},
        { label: 'oc-FR', description: 'Occitan (France)'},
        { label: 'or-IN', description: 'Oriya (India)'},
        { label: 'ps-AF', description: 'Pashto (Afghanistan)'},
        { label: 'fa-IR', description: 'Persian'},
        { label: 'pl-PL', description: 'Polish (Poland)'},
        { label: 'pt-BR', description: 'Portuguese (Brazil)'},
        { label: 'pt-PT', description: 'Portuguese (Portugal)'},
        { label: 'pa-IN', description: 'Punjabi (India)'},
        { label: 'quz-BO', description: 'Quechua (Bolivia)'},
        { label: 'quz-EC', description: 'Quechua (Ecuador)'},
        { label: 'quz-PE', description: 'Quechua (Peru)'},
        { label: 'ro-RO', description: 'Romanian (Romania)'},
        { label: 'rm-CH', description: 'Romansh (Switzerland)'},
        // { label: 'ru-RU', description: 'Russian (Russia)'},
        { label: 'smn-FI', description: 'Sami, Inari (Finland)'},
        { label: 'smj-NO', description: 'Sami, Lule (Norway)'},
        { label: 'smj-SE', description: 'Sami, Lule (Sweden)'},
        { label: 'se-FI', description: 'Sami, Northern (Finland)'},
        { label: 'se-NO', description: 'Sami, Northern (Norway)'},
        { label: 'se-SE', description: 'Sami, Northern (Sweden)'},
        { label: 'sms-FI', description: 'Sami, Skolt (Finland)'},
        { label: 'sma-NO', description: 'Sami, Southern (Norway)'},
        { label: 'sma-SE', description: 'Sami, Southern (Sweden)'},
        { label: 'sa-IN', description: 'Sanskrit (India)'},
        { label: 'sr-Cyrl-BA', description: 'Serbian (Cyrillic, Bosnia and Herzegovina)'},
        { label: 'sr-Cyrl-SP', description: 'Serbian (Cyrillic, Serbia)'},
        { label: 'sr-Latn-BA', description: 'Serbian (Latin, Bosnia and Herzegovina)'},
        { label: 'sr-Latn-SP', description: 'Serbian (Latin, Serbia)'},
        { label: 'nso-ZA', description: 'Sesotho sa Leboa (South Africa)'},
        { label: 'tn-ZA', description: 'Setswana (South Africa)'},
        { label: 'si-LK', description: 'Sinhala (Sri Lanka)'},
        { label: 'sk-SK', description: 'Slovak (Slovakia)'},
        { label: 'sl-SI', description: 'Slovenian (Slovenia)'},
        { label: 'es-AR', description: 'Spanish (Argentina)'},
        { label: 'es-BO', description: 'Spanish (Bolivia)'},
        { label: 'es-CL', description: 'Spanish (Chile)'},
        { label: 'es-CO', description: 'Spanish (Colombia)'},
        { label: 'es-CR', description: 'Spanish (Costa Rica)'},
        { label: 'es-DO', description: 'Spanish (Dominican Republic)'},
        { label: 'es-EC', description: 'Spanish (Ecuador)'},
        { label: 'es-SV', description: 'Spanish (El Salvador)'},
        { label: 'es-GT', description: 'Spanish (Guatemala)'},
        { label: 'es-HN', description: 'Spanish (Honduras)'},
        { label: 'es-MX', description: 'Spanish (Mexico)'},
        { label: 'es-NI', description: 'Spanish (Nicaragua)'},
        { label: 'es-PA', description: 'Spanish (Panama)'},
        { label: 'es-PY', description: 'Spanish (Paraguay)'},
        { label: 'es-PE', description: 'Spanish (Peru)'},
        { label: 'es-PR', description: 'Spanish (Puerto Rico)'},
        // { label: 'es-ES', description: 'Spanish (Spain)'},
        { label: 'es-US', description: 'Spanish (United States)'},
        { label: 'es-UY', description: 'Spanish (Uruguay)'},
        { label: 'es-VE', description: 'Spanish (Venezuela)'},
        { label: 'sv-FI', description: 'Swedish (Finland)'},
        { label: 'sv-SE', description: 'Swedish (Sweden)'},
        { label: 'syr-SY', description: 'Syriac (Syria)'},
        { label: 'tg-TJ', description: 'Tajik (Tajikistan)'},
        { label: 'tzm-DZ', description: 'Tamazight (Algeria)'},
        { label: 'ta-IN', description: 'Tamil (India)'},
        { label: 'tt-RU', description: 'Tatar (Russia)'},
        { label: 'te-IN', description: 'Telugu (India)'},
        { label: 'th-TH', description: 'Thai (Thailand)'},
        { label: 'bo-CN', description: 'Tibetan (PRC)'},
        { label: 'tr-TR', description: 'Turkish (Turkey)'},
        { label: 'tk-TM', description: 'Turkmen (Turkmenistan)'},
        { label: 'ug-CN', description: 'Uighur (PRC)'},
        { label: 'uk-UA', description: 'Ukrainian (Ukraine)'},
        { label: 'wen-DE', description: 'Upper Sorbian (Germany)'},
        { label: 'ur-PK', description: 'Urdu (Islamic Republic of Pakistan)'},
        { label: 'uz-UZ', description: 'Uzbek (Uzbekistan)'},
        { label: 'vi-VN', description: 'Vietnamese (Vietnam)'},
        { label: 'cy-GB', description: 'Welsh (United Kingdom)'},
        { label: 'wo-SN', description: 'Wolof (Senegal)'},
        { label: 'sah-RU', description: 'Yakut (Russia)'},
        { label: 'ii-CN', description: 'Yi (PRC)'},
        { label: 'yo-NG', description: 'Yoruba (Nigeria)'}
    ];

    private static RFC5646LanguageTagList: QuickPickItem[] = [
        { label: 'en-US', description: 'English (United States)'},
        { label: 'fr-FR', description: 'French (France)'},
        { label: 'es-ES', description: 'Spanish (Spain)'},
        { label: 'de-DE', description: 'German (Germany)'},
        { label: 'ru-RU', description: 'Russian (Russia)'},
        { label: 'zh-CN', description: 'Chinese (Simplified)'},
        { label: 'zh-TW', description: 'Chinese (Traditional)'},
        { label: 'ko-KR', description: 'Korean (Korea)'},
        { label: 'ja-JP', description: 'Japanese (Japan)'},
        { label: 'it-IT', description: 'Italian (Italy)'},
        { label: 'da-DK', description: 'Danish (Denmark)'},
        { label: 'fi-FI', description: 'Finnish (Finland)'},
        { label: 'nl-NL', description: 'Dutch (Netherlands)'},
        { label: 'nb-NO', description: 'Norwegian Bokmål (Norway)'},
        { label: 'af', description: 'Afrikaans'},
        { label: 'af-ZA', description: 'Afrikaans (South Africa)'},
        { label: 'ar', description: 'Arabic'},
        { label: 'ar-AE', description: 'Arabic (U.A.E.)'},
        { label: 'ar-BH', description: 'Arabic (Bahrain)'},
        { label: 'ar-DZ', description: 'Arabic (Algeria)'},
        { label: 'ar-EG', description: 'Arabic (Egypt)'},
        { label: 'ar-IQ', description: 'Arabic (Iraq)'},
        { label: 'ar-JO', description: 'Arabic (Jordan)'},
        { label: 'ar-KW', description: 'Arabic (Kuwait)'},
        { label: 'ar-LB', description: 'Arabic (Lebanon)'},
        { label: 'ar-LY', description: 'Arabic (Libya)'},
        { label: 'ar-MA', description: 'Arabic (Morocco)'},
        { label: 'ar-OM', description: 'Arabic (Oman)'},
        { label: 'ar-QA', description: 'Arabic (Qatar)'},
        { label: 'ar-SA', description: 'Arabic (Saudi Arabia)'},
        { label: 'ar-SY', description: 'Arabic (Syria)'},
        { label: 'ar-TN', description: 'Arabic (Tunisia)'},
        { label: 'ar-YE', description: 'Arabic (Yemen)'},
        { label: 'az', description: 'Azeri (Latin)'},
        { label: 'az-AZ', description: 'Azeri (Latin) (Azerbaijan)'},
        { label: 'az-Cyrl-AZ', description: 'Azeri (Cyrillic) (Azerbaijan)'},
        { label: 'be', description: 'Belarusian'},
        { label: 'be-BY', description: 'Belarusian (Belarus)'},
        { label: 'bg', description: 'Bulgarian'},
        { label: 'bg-BG', description: 'Bulgarian (Bulgaria)'},
        { label: 'bs-BA', description: 'Bosnian (Bosnia and Herzegovina)'},
        { label: 'ca', description: 'Catalan'},
        { label: 'ca-ES', description: 'Catalan (Spain)'},
        { label: 'cs', description: 'Czech'},
        { label: 'cs-CZ', description: 'Czech (Czech Republic)'},
        { label: 'cy', description: 'Welsh'},
        { label: 'cy-GB', description: 'Welsh (United Kingdom)'},
        { label: 'da', description: 'Danish'},
        // { label: 'da-DK', description: 'Danish (Denmark)'},
        { label: 'de', description: 'German'},
        { label: 'de-AT', description: 'German (Austria)'},
        { label: 'de-CH', description: 'German (Switzerland)'},
        // { label: 'de-DE', description: 'German (Germany)'},
        { label: 'de-LI', description: 'German (Liechtenstein)'},
        { label: 'de-LU', description: 'German (Luxembourg)'},
        { label: 'dv', description: 'Divehi'},
        { label: 'dv-MV', description: 'Divehi (Maldives)'},
        { label: 'el', description: 'Greek'},
        { label: 'el-GR', description: 'Greek (Greece)'},
        { label: 'en', description: 'English'},
        { label: 'en-AU', description: 'English (Australia)'},
        { label: 'en-BZ', description: 'English (Belize)'},
        { label: 'en-CA', description: 'English (Canada)'},
        { label: 'en-CB', description: 'English (Caribbean)'},
        { label: 'en-GB', description: 'English (United Kingdom)'},
        { label: 'en-IE', description: 'English (Ireland)'},
        { label: 'en-JM', description: 'English (Jamaica)'},
        { label: 'en-NZ', description: 'English (New Zealand)'},
        { label: 'en-PH', description: 'English (Republic of the Philippines)'},
        { label: 'en-TT', description: 'English (Trinidad and Tobago)'},
        // { label: 'en-US', description: 'English (United States)'},
        { label: 'en-ZA', description: 'English (South Africa)'},
        { label: 'en-ZW', description: 'English (Zimbabwe)'},
        { label: 'eo', description: 'Esperanto'},
        { label: 'es', description: 'Spanish'},
        { label: 'es-AR', description: 'Spanish (Argentina)'},
        { label: 'es-BO', description: 'Spanish (Bolivia)'},
        { label: 'es-CL', description: 'Spanish (Chile)'},
        { label: 'es-CO', description: 'Spanish (Colombia)'},
        { label: 'es-CR', description: 'Spanish (Costa Rica)'},
        { label: 'es-DO', description: 'Spanish (Dominican Republic)'},
        { label: 'es-EC', description: 'Spanish (Ecuador)'},
        // { label: 'es-ES', description: 'Spanish (Spain)'},
        { label: 'es-GT', description: 'Spanish (Guatemala)'},
        { label: 'es-HN', description: 'Spanish (Honduras)'},
        { label: 'es-MX', description: 'Spanish (Mexico)'},
        { label: 'es-NI', description: 'Spanish (Nicaragua)'},
        { label: 'es-PA', description: 'Spanish (Panama)'},
        { label: 'es-PE', description: 'Spanish (Peru)'},
        { label: 'es-PR', description: 'Spanish (Puerto Rico)'},
        { label: 'es-PY', description: 'Spanish (Paraguay)'},
        { label: 'es-SV', description: 'Spanish (El Salvador)'},
        { label: 'es-UY', description: 'Spanish (Uruguay)'},
        { label: 'es-VE', description: 'Spanish (Venezuela)'},
        { label: 'et', description: 'Estonian'},
        { label: 'et-EE', description: 'Estonian (Estonia)'},
        { label: 'eu', description: 'Basque'},
        { label: 'eu-ES', description: 'Basque (Spain)'},
        { label: 'fa', description: 'Farsi'},
        { label: 'fa-IR', description: 'Farsi (Iran)'},
        { label: 'fi', description: 'Finnish'},
        // { label: 'fi-FI', description: 'Finnish (Finland)'},
        { label: 'fo', description: 'Faroese'},
        { label: 'fo-FO', description: 'Faroese (Faroe Islands)'},
        { label: 'fr', description: 'French'},
        { label: 'fr-BE', description: 'French (Belgium)'},
        { label: 'fr-CA', description: 'French (Canada)'},
        { label: 'fr-CH', description: 'French (Switzerland)'},
        // { label: 'fr-FR', description: 'French (France)'},
        { label: 'fr-LU', description: 'French (Luxembourg)'},
        { label: 'fr-MC', description: 'French (Principality of Monaco)'},
        { label: 'gl', description: 'Galician'},
        { label: 'gl-ES', description: 'Galician (Spain)'},
        { label: 'gu', description: 'Gujarati'},
        { label: 'gu-IN', description: 'Gujarati (India)'},
        { label: 'he', description: 'Hebrew'},
        { label: 'he-IL', description: 'Hebrew (Israel)'},
        { label: 'hi', description: 'Hindi'},
        { label: 'hi-IN', description: 'Hindi (India)'},
        { label: 'hr', description: 'Croatian'},
        { label: 'hr-BA', description: 'Croatian (Bosnia and Herzegovina)'},
        { label: 'hr-HR', description: 'Croatian (Croatia)'},
        { label: 'hu', description: 'Hungarian'},
        { label: 'hu-HU', description: 'Hungarian (Hungary)'},
        { label: 'hy', description: 'Armenian'},
        { label: 'hy-AM', description: 'Armenian (Armenia)'},
        { label: 'id', description: 'Indonesian'},
        { label: 'id-ID', description: 'Indonesian (Indonesia)'},
        { label: 'is', description: 'Icelandic'},
        { label: 'is-IS', description: 'Icelandic (Iceland)'},
        { label: 'it', description: 'Italian'},
        { label: 'it-CH', description: 'Italian (Switzerland)'},
        // { label: 'it-IT', description: 'Italian (Italy)'},
        { label: 'ja', description: 'Japanese'},
        // { label: 'ja-JP', description: 'Japanese (Japan)'},
        { label: 'ka', description: 'Georgian'},
        { label: 'ka-GE', description: 'Georgian (Georgia)'},
        { label: 'kk', description: 'Kazakh'},
        { label: 'kk-KZ', description: 'Kazakh (Kazakhstan)'},
        { label: 'kn', description: 'Kannada'},
        { label: 'kn-IN', description: 'Kannada (India)'},
        { label: 'ko', description: 'Korean'},
        // { label: 'ko-KR', description: 'Korean (Korea)'},
        { label: 'kok', description: 'Konkani'},
        { label: 'kok-IN', description: 'Konkani (India)'},
        { label: 'ky', description: 'Kyrgyz'},
        { label: 'ky-KG', description: 'Kyrgyz (Kyrgyzstan)'},
        { label: 'lt', description: 'Lithuanian'},
        { label: 'lt-LT', description: 'Lithuanian (Lithuania)'},
        { label: 'lv', description: 'Latvian'},
        { label: 'lv-LV', description: 'Latvian (Latvia)'},
        { label: 'mi', description: 'Maori'},
        { label: 'mi-NZ', description: 'Maori (New Zealand)'},
        { label: 'mk', description: 'FYRO Macedonian'},
        { label: 'mk-MK', description: 'FYRO Macedonian (Former Yugoslav Republic of Macedonia)'},
        { label: 'mn', description: 'Mongolian'},
        { label: 'mn-MN', description: 'Mongolian (Mongolia)'},
        { label: 'mr', description: 'Marathi'},
        { label: 'mr-IN', description: 'Marathi (India)'},
        { label: 'ms', description: 'Malay'},
        { label: 'ms-BN', description: 'Malay (Brunei Darussalam)'},
        { label: 'ms-MY', description: 'Malay (Malaysia)'},
        { label: 'mt', description: 'Maltese'},
        { label: 'mt-MT', description: 'Maltese (Malta)'},
        { label: 'nb', description: 'Norwegian (Bokmål)'},
        // { label: 'nb-NO', description: 'Norwegian Bokmål (Norway)'},
        { label: 'nl', description: 'Dutch'},
        { label: 'nl-BE', description: 'Dutch (Belgium)'},
        // { label: 'nl-NL', description: 'Dutch (Netherlands)'},
        { label: 'nn-NO', description: 'Norwegian (Nynorsk) (Norway)'},
        { label: 'ns', description: 'Northern Sotho'},
        { label: 'ns-ZA', description: 'Northern Sotho (South Africa)'},
        { label: 'pa', description: 'Punjabi'},
        { label: 'pa-IN', description: 'Punjabi (India)'},
        { label: 'pl', description: 'Polish'},
        { label: 'pl-PL', description: 'Polish (Poland)'},
        { label: 'ps', description: 'Pashto'},
        { label: 'ps-AR', description: 'Pashto (Afghanistan)'},
        { label: 'pt', description: 'Portuguese'},
        { label: 'pt-BR', description: 'Portuguese (Brazil)'},
        { label: 'pt-PT', description: 'Portuguese (Portugal)'},
        { label: 'qu', description: 'Quechua'},
        { label: 'qu-BO', description: 'Quechua (Bolivia)'},
        { label: 'qu-EC', description: 'Quechua (Ecuador)'},
        { label: 'qu-PE', description: 'Quechua (Peru)'},
        { label: 'ro', description: 'Romanian'},
        { label: 'ro-RO', description: 'Romanian (Romania)'},
        { label: 'ru', description: 'Russian'},
        // { label: 'ru-RU', description: 'Russian (Russia)'},
        { label: 'sa', description: 'Sanskrit'},
        { label: 'sa-IN', description: 'Sanskrit (India)'},
        { label: 'se', description: 'Sami'},
        { label: 'se-FI', description: 'Sami (Finland)'},
        { label: 'se-NO', description: 'Sami (Norway)'},
        { label: 'se-SE', description: 'Sami (Sweden)'},
        { label: 'sk', description: 'Slovak'},
        { label: 'sk-SK', description: 'Slovak (Slovakia)'},
        { label: 'sl', description: 'Slovenian'},
        { label: 'sl-SI', description: 'Slovenian (Slovenia)'},
        { label: 'sq', description: 'Albanian'},
        { label: 'sq-AL', description: 'Albanian (Albania)'},
        { label: 'sr-BA', description: 'Serbian (Latin) (Bosnia and Herzegovina)'},
        { label: 'sr-Cyrl-BA', description: 'Serbian (Cyrillic) (Bosnia and Herzegovina)'},
        { label: 'sr-SP', description: 'Serbian (Latin) (Serbia and Montenegro)'},
        { label: 'sr-Cyrl-SP', description: 'Serbian (Cyrillic) (Serbia and Montenegro)'},
        { label: 'sv', description: 'Swedish'},
        { label: 'sv-FI', description: 'Swedish (Finland)'},
        { label: 'sv-SE', description: 'Swedish (Sweden)'},
        { label: 'sw', description: 'Swahili'},
        { label: 'sw-KE', description: 'Swahili (Kenya)'},
        { label: 'syr', description: 'Syriac'},
        { label: 'syr-SY', description: 'Syriac (Syria)'},
        { label: 'ta', description: 'Tamil'},
        { label: 'ta-IN', description: 'Tamil (India)'},
        { label: 'te', description: 'Telugu'},
        { label: 'te-IN', description: 'Telugu (India)'},
        { label: 'th', description: 'Thai'},
        { label: 'th-TH', description: 'Thai (Thailand)'},
        { label: 'tl', description: 'Tagalog'},
        { label: 'tl-PH', description: 'Tagalog (Philippines)'},
        { label: 'tn', description: 'Tswana'},
        { label: 'tn-ZA', description: 'Tswana (South Africa)'},
        { label: 'tr', description: 'Turkish'},
        { label: 'tr-TR', description: 'Turkish (Turkey)'},
        { label: 'tt', description: 'Tatar'},
        { label: 'tt-RU', description: 'Tatar (Russia)'},
        { label: 'ts', description: 'Tsonga'},
        { label: 'uk', description: 'Ukrainian'},
        { label: 'uk-UA', description: 'Ukrainian (Ukraine)'},
        { label: 'ur', description: 'Urdu'},
        { label: 'ur-PK', description: 'Urdu (Islamic Republic of Pakistan)'},
        { label: 'uz', description: 'Uzbek (Latin)'},
        { label: 'uz-UZ', description: 'Uzbek (Latin) (Uzbekistan)'},
        { label: 'uz-Cyrl-UZ', description: 'Uzbek (Cyrillic) (Uzbekistan)'},
        { label: 'vi', description: 'Vietnamese'},
        { label: 'vi-VN', description: 'Vietnamese (Viet Nam)'},
        { label: 'xh', description: 'Xhosa'},
        { label: 'xh-ZA', description: 'Xhosa (South Africa)'},
        { label: 'zh', description: 'Chinese'},
        // { label: 'zh-CN', description: 'Chinese (Simplified)'},
        { label: 'zh-HK', description: 'Chinese (Hong Kong)'},
        { label: 'zh-MO', description: 'Chinese (Macau)'},
        { label: 'zh-SG', description: 'Chinese (Singapore)'},
        // { label: 'zh-TW', description: 'Chinese (Traditional)'},
        { label: 'zu', description: 'Zulu'},
        { label: 'zu-ZA', description: 'Zulu (South Africa)'}
    ];

    public static getRFC4646LanguageTagList(): QuickPickItem[] {
        return this.RFC4646LanguageTagList;
    }

    public static getRFC5646LanguageTagList(): QuickPickItem[] {
        return this.RFC5646LanguageTagList;
    }

    public static getLanguageTagList(fileType: string): QuickPickItem[] {
        switch (fileType) {
            case 'xlf':
                return this.getRFC4646LanguageTagList();
            case 'xlf2':
                return this.getRFC5646LanguageTagList();
            default:
                return [];
        }
    }
}
